// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
insert into accounts (id, user_id, name, avatar, gender, signature)
values (?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID        int64
	UserID    int64
	Name      string
	Avatar    string
	Gender    AccountsGender
	Signature string
}

func (q *Queries) CreateAccount(ctx context.Context, arg *CreateAccountParams) error {
	_, err := q.exec(ctx, q.createAccountStmt, createAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Avatar,
		arg.Gender,
		arg.Signature,
	)
	return err
}
