// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: file.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :exec
insert into files (file_name, file_type, file_size, ` + "`" + `key` + "`" + `, url, relation_id, account_id)
values(?,?,?,?,?,?,?)
`

type CreateFileParams struct {
	FileName   string
	FileType   FilesFileType
	FileSize   int64
	Key        string
	Url        string
	RelationID sql.NullInt64
	AccountID  sql.NullInt64
}

func (q *Queries) CreateFile(ctx context.Context, arg *CreateFileParams) error {
	_, err := q.exec(ctx, q.createFileStmt, createFile,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Key,
		arg.Url,
		arg.RelationID,
		arg.AccountID,
	)
	return err
}

const createFileReturn = `-- name: CreateFileReturn :one
select (file_name, file_type, file_size, ` + "`" + `key` + "`" + `, url, relation_id, account_id)
from files
where last_insert_id()
`

func (q *Queries) CreateFileReturn(ctx context.Context) (interface{}, error) {
	row := q.queryRow(ctx, q.createFileReturnStmt, createFileReturn)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
delete
from files
where id = ?
`

func (q *Queries) DeleteFileByID(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteFileByIDStmt, deleteFileByID, id)
	return err
}

const getFileByRelation = `-- name: GetFileByRelation :many
select id, file_name, file_type, file_size, ` + "`" + `key` + "`" + `, url, relation_id, account_id, create_at
from files
where relation_id = ?
`

func (q *Queries) GetFileByRelation(ctx context.Context, relationID sql.NullInt64) ([]*File, error) {
	rows, err := q.query(ctx, q.getFileByRelationStmt, getFileByRelation, relationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Key,
			&i.Url,
			&i.RelationID,
			&i.AccountID,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByRelationIDIsNULL = `-- name: GetFileByRelationIDIsNULL :many
SELECT id, ` + "`" + `key` + "`" + `
FROM files
WHERE relation_id IS NULL AND file_name != 'AccountAvatar'
`

type GetFileByRelationIDIsNULLRow struct {
	ID  int64
	Key string
}

func (q *Queries) GetFileByRelationIDIsNULL(ctx context.Context) ([]*GetFileByRelationIDIsNULLRow, error) {
	rows, err := q.query(ctx, q.getFileByRelationIDIsNULLStmt, getFileByRelationIDIsNULL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFileByRelationIDIsNULLRow{}
	for rows.Next() {
		var i GetFileByRelationIDIsNULLRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileDetailsByID = `-- name: GetFileDetailsByID :one
select id, file_name, file_type, file_size, ` + "`" + `key` + "`" + `, url, relation_id, account_id, create_at
from files
where id = ?
`

func (q *Queries) GetFileDetailsByID(ctx context.Context, id int64) (*File, error) {
	row := q.queryRow(ctx, q.getFileDetailsByIDStmt, getFileDetailsByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const getFileKeyByID = `-- name: GetFileKeyByID :one
select ` + "`" + `key` + "`" + `
from files
where id = ?
`

func (q *Queries) GetFileKeyByID(ctx context.Context, id int64) (string, error) {
	row := q.queryRow(ctx, q.getFileKeyByIDStmt, getFileKeyByID, id)
	var key string
	err := row.Scan(&key)
	return key, err
}

const getGroupAvatar = `-- name: GetGroupAvatar :one
SELECT id, file_name, file_type, file_size, ` + "`" + `key` + "`" + `, url, relation_id, account_id, create_at
FROM files
WHERE relation_id = ?
  AND account_id IS NULL
`

func (q *Queries) GetGroupAvatar(ctx context.Context, relationID sql.NullInt64) (*File, error) {
	row := q.queryRow(ctx, q.getGroupAvatarStmt, getGroupAvatar, relationID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const updateGroupAvatar = `-- name: UpdateGroupAvatar :exec
UPDATE files
SET url = ?
WHERE relation_id = ? AND file_name = 'groupAvatar'
`

type UpdateGroupAvatarParams struct {
	Url        string
	RelationID sql.NullInt64
}

func (q *Queries) UpdateGroupAvatar(ctx context.Context, arg *UpdateGroupAvatarParams) error {
	_, err := q.exec(ctx, q.updateGroupAvatarStmt, updateGroupAvatar, arg.Url, arg.RelationID)
	return err
}
