mysql:
  DriverName: mysql # 驱动名称
  SourceName: user=root password=123456 host=123.249.32.125 port=3306 dbname=ChatRoom sslmode=disable # 数据源名称
###############################################################
#Redis:
#  Address: 123.249.32.125:6379 # redis 服务器地址
#  DB: 0 # redis 数据库索引（0-15）
#  Password: 1234. # 认证密码
#  PoolSize: 100 # redis 连接池大小
#  CacheTime: 10m # redis 缓存时间
###############################################################
RedisCluster:
  Nodes:
    - Address: 123.249.32.125:6381 # 主节点
      Role: master
      Password: 1234
    - Address: 123.249.32.125:6384 # 从节点
      Role: slave
      Password: 1234
    - Address: 123.249.32.125:6382 # 主节点
      Role: master
      Password: 1234
    - Address: 123.249.32.125:6385 # 从节点
      Role: slave
      Password: 1234
    - Address: 123.249.32.125:6383 # 主节点
      Role: master
      Password: 1234
    - Address: 123.249.32.125:6386 # 从节点
      Role: slave
      Password: 1234
  ClusterEnabled: true
  PoolSize: 100 # 集群连接池大小
  CacheTime: 10m # 集群缓存时间
Email:
  Password: pmuereghhhoeibee
  IsSSL: true # 是否使用 SSL 加密
  Host: smtp.qq.com # 邮箱服务器的主机地址，smtp.qq.com 是 QQ 邮件的 SMTP
  Port: 465 # 邮箱服务器端口号
  Username: 1492568061@qq.com
  From: 1492568061@qq.com
  To:
    - 1492568061@qq.com
Token:
  Key: tqgymXijyHpZbeoXcOexVBHbBsBlDNrm # 密钥（必须是32个字节，因为我们使用的是 chacha20poly1305 加密算法）
  AccessTokenExpire: 168h # 用户 token 的访问令牌
  RefreshTokenExpire: 720h # 用户 token 的刷新令牌
  AccountTokenDuration: 24h # 账户 token 的有效期限
  AuthorizationKey: Authorization
  AuthorizationType: Bearer
HuaWeiOBS:
  BucketName: chatroom-bucket # 存储桶名称
  BucketUrl: https://chatroom-bucket.obs.cn-north-4.myhuaweicloud.com # 存储桶 URL
  Location: cn-north-4 # 华北-北京四
  Endpoint: https://obs.cn-north-4.myhuaweicloud.com # 华北-北京四
  BasePath: uploads/ # 上传文件时，文件在存储桶中的基础路径
  AvatarType: NotAvatar
  AccountAvatarUrl: account_avatars/
  GroupAvatarUrl: group_avatars/ # 群组头像 URL
RocketMQ:
  Addr: "123.249.32.125"
  Port: 9876