Mysql:
  DriverName: mysql # 驱动名称
  SourceName: root:123456@tcp(123.249.32.125:3306)/chatroom?charset=utf8mb4&parseTime=True
#  SourceName: user=root password=123456 host=123.249.32.125 port=3306 dbname=ChatRoom sslmode=disable # 数据源名称
###############################################################
#Redis:
#  Address: 123.249.32.125:6379 # redis 服务器地址
#  DB: 0 # redis 数据库索引（0-15）
#  Password: 1234. # 认证密码
#  PoolSize: 100 # redis 连接池大小
#  CacheTime: 10m # redis 缓存时间
###############################################################
#RedisCluster:
#  Nodes:
#    - Address: 123.249.32.125:6381 # 主节点
#      Role: master
#      Password: 1234
#    - Address: 123.249.32.125:6384 # 从节点
#      Role: slave
#      Password: 1234
#    - Address: 123.249.32.125:6382 # 主节点
#      Role: master
#      Password: 1234
#    - Address: 123.249.32.125:6385 # 从节点
#      Role: slave
#      Password: 1234
#    - Address: 123.249.32.125:6383 # 主节点
#      Role: master
#      Password: 1234
#    - Address: 123.249.32.125:6386 # 从节点
#      Role: slave
#      Password: 1234
#  ClusterEnabled: true
#  PoolSize: 100 # 集群连接池大小
#  CacheTime: 10m # 集群缓存时间
###########################################################
RedisCluster:
  # 集群节点地址列表（只需主节点或任意可达节点，客户端会自动发现拓扑）
  Endpoints:
    - "123.249.32.125:6381"
    - "123.249.32.125:6382"
    - "123.249.32.125:6383"

  # 全局认证密码（主从密码一致时可简写）
  Password: "1234"

  # 连接池配置
  PoolConfig:
    PoolSize: 100          # 连接池大小
    MinIdleConns: 10       # 最小空闲连接
    ConnectTimeout: 5s     # 连接超时
    ReadTimeout: 3s        # 读操作超时
    WriteTimeout: 3s       # 写操作超时

  # 集群特性配置
  ClusterConfig:
    MaxRedirects: 8        # 最大重定向次数（默认8）
    RouteByLatency: false   # 是否启用延迟路由（慎用）
    RouteRandomly: false    # 是否随机路由

  # TLS 配置（可选）
  TLS:
    Enable: false
    CertFile: ""
    KeyFile: ""
    CAFile: ""

  # 高级配置
  CacheTime: 10m            # 元数据缓存时间（如集群拓扑信息）
  ReadOnly: false           # 是否启用只读模式
  DisableAutoReconnect: false # 是否禁用自动重连
###########################################################################
Email:
  Password: pmuereghhhoeibee
  IsSSL: true # 是否使用 SSL 加密
  Host: smtp.qq.com # 邮箱服务器的主机地址，smtp.qq.com 是 QQ 邮件的 SMTP
  Port: 465 # 邮箱服务器端口号
  Username: 1492568061@qq.com
  From: 1492568061@qq.com
  To:
    - 1492568061@qq.com
Token:
  Key: tqgymXijyHpZbeoXcOexVBHbBsBlDNrm # 密钥（必须是32个字节，因为我们使用的是 chacha20poly1305 加密算法）
  AccessTokenExpire: 168h # 用户 token 的访问令牌
  RefreshTokenExpire: 720h # 用户 token 的刷新令牌
  AccountTokenDuration: 24h # 账户 token 的有效期限
  AuthorizationKey: Authorization
  NewAuthorizationKey: AccountToken
  AuthorizationType: Bearer
HuaWeiOBS:
  BucketName: chatroom-bucket # 存储桶名称
  BucketUrl: https://chatroom-bucket.oss-cn-beijing.aliyuncs.com # 存储桶 URL
  Location: cn-beijing # 北京
  Endpoint: https://oss-cn-beijing.aliyuncs.com # 北京
  BasePath: uploads/ # 上传文件时，文件在存储桶中的基础路径
  AvatarType: NotAvatar
  AccountAvatarUrl: account_avatars/
  GroupAvatarUrl: group_avatars/ # 群组头像 URL
RocketMQ:
  Addr: "123.249.32.125"
  Port: 9092